### ISSUE TITLE
Error in count(txt, section) : object 'section' not found

### ISSUE THREAD

**Issue by kcmtest** [cstubben/tidypmc#3]
```
```
```
library(tidypmc)
doc <- pmc_xml("PMC2231364")
doc
txt <- pmc_text(doc)

count(txt, section)

Error in count(txt, section) : object 'section' not found
--
 
```
  |  
 

```

```

Im running exactly shown in the code but i end up with this error. I tried converitng it into data frame but still it doesn't work.I would be glad if you can let me know if im doing something wrong here..

**Comment by kcmtest** [comment]
> ```
> library(tidypmc)
> doc <- pmc_xml("PMC2231364")
> doc
> txt <- pmc_text(doc)
> 
> count(txt, section)
> 
> Error in count(txt, section) : object 'section' not found
> --
>  
> ```
> 
>   |  
>  
> 
> ```
> 
> ```
> 
> Im running exactly shown in the code but i end up with this error. I tried converitng it into data frame but still it doesn't work.I would be glad if you can let me know if im doing something wrong here..


`count(txt, "section") when i used this i got the frequency 
`

**Comment by cstubben** [comment]
That's a weird error and I'm not sure why quoting "section" fixes it - count is a function in many different packages and I often have to use dplyr::count

```
dplyr::count(txt, section)
# A tibble: 21 x 2
   section                                                  n
   <chr>                                                <int>
 1 Abstract                                                 8
 2 Authors' contributions                                   6
 3 Background                                              20
 4 Conclusion                                               3
 5 Methods; Clustering analysis                             7
 6 Methods; Collection of microarray expression data       17
....
```

**Comment by kcmtest** [comment]
well even im not sure what is going on..meanwhile i have a question is there a way where i can put all the PMCID in a loop and parse through .If you can show me with a little example I would be really glad..I been trying but not sure how to do it.

**Comment by kcmtest** [comment]
```
library(tidypmc)
doc <- pmc_xml("PMC6365492")
doc
txt <- pmc_text(doc)
txt

count(txt, "section")

cap1 <- pmc_caption(doc)
filter(cap1, sentence == 1)

tab1 <- pmc_table(doc)

sapply(tab1, nrow)

tab1[[1]]
attributes(tab1[[2]])

collapse_rows(tab1, na.string="-")

x <- separate_refs(txt)

separate_genes(txt)

library(tibble)
x <- xml_name(xml_find_all(doc, "//*"))
tibble(tag=x) %>% count("tag")

library(tidytext)
x1 <- unnest_tokens(txt, word, text) %>%
  anti_join(stop_words) %>%
  filter(!word %in% 1:100)
#  Joining, by = "word"
#filter(x1, str_detect(section, "Case description")) 


filter(x1, str_detect(section, "Results"))
count(a$word)

tbls <- pmc_table(doc)
map_int(tbls, nrow)

tbls[[1]]

collapse_rows(tbls, na.string="-")
separate_refs(txt)
separate_genes(txt)

separate_text(txt, "death")

```
Right now I'm using this which in your vignette shows, can you tell me how can i put them in loop such as from every PMCID which is parsed it should be stored in a dataframe with a ID and respective results in in subsequent columns

**Comment by cstubben** [comment]
If you have a vector of PMC ids like pmcids below, I would use a loop - some PMC XML is badly formatted and you will eventually see errors that you can skip, for example if #9 fails to parse, just restart the loop using for (i in 10:21).   Also, it looks like PMC ids are now missing from the PMC XML, so I need to update my pmc_metadata code (and the FTP vignette since met$PMCID does not exist).   

```
library(tidypmc)
library(europepmc)
yp <- epmc_search("title:(Yersinia pestis virulence) OPEN_ACCESS:Y")
# 21 records found, returning 21

pmcids <- yp$pmcid
n <- length(pmcids)

txt1 <- vector("list", n)
for(i in seq_len(n)){
  id <- pmcids[i]
  message("Parsing ", i, ". ", id) 
  doc <- pmc_xml(id)
  txt1[[i]] <- pmc_text(doc)
  # always nice to pause for 1 to 3 seconds
  # Sys.sleep(sample(1:3))  
}

library(dplyr)
names(txt1) <- pmcids
txt <- bind_rows(txt1, .id="PMCID")
txt
```

**Comment by kcmtest** [comment]
"If you have a vector of PMC ids like pmcids below" using europmc i did take out IDs which has PMCID ..so i can use those which has open access only .

I did ask the issue over stack this is one of the answer i was suggested since i was not sure how to create a function 

[https://bioinformatics.stackexchange.com/questions/13984/europmc-and-tidypmc-r-library-for-extracting-or-making-metadata-from-publication/14027#14027](url)

**Comment by kcmtest** [comment]
```
b <-epmc_search(query = 'acute myeloid leukemia drug studies',output = 'parsed',limit = 200)
a <- b %>% select(pmid)
a <- a[complete.cases(a),]
c <- a$pmid


#-- Convert to PMC ids
convertPIDtoPMCID <- function(pids) {
  #-------- Make API request
  pids4query <- paste(pids, collapse = "%0D%0A")
  idconv_req <- paste0("https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/?ids=", pids4query, "&idtype=pmid&format=json&versions=no&showaiid=no&tool=&email=&.submit=Submit")
  pids_json <- GET(idconv_req) %>% content("text") %>% fromJSON()
  #-------- Get info from JSON
  pid2pmc <- pids_json$records %>% 
    select(pmcid, pmid) %>% 
    as.data.frame()
  rownames(pid2pmc) <- pid2pmc$pmid
  pmcids <- pmcids <- pid2pmc[pids, "pmcid"]
  return(pmcids)
}
example_pmcids <- convertPIDtoPMCID(c)

#-- Try to get data with tidypmc
pub_tables <- lapply(example_pmcids, function(pmc_id) {
  message("-- Trying ", pmc_id, "...")
  doc <- tryCatch(pmc_xml(pmc_id), 
                  error = function(e) {
                    message("------ Failed to recover PMCID")
                    return(NULL)
                  })
  if(!is.null(doc)) { 
    #-- If succeed, try to get table
    tables <- pmc_table(doc)
    if(!is.null(tables)) {
      #-- If succeed, try to get table name
      table_caps <- pmc_caption(doc) %>%
        filter(tag == "table")
      names(tables) <- paste(table_caps$label, table_caps$text, sep = " - ")
    }
    return(tables) 
  } else {
    #-- If fail, return NA
    return(NA)
  }
})
names(pub_tables) <- example_pids
```

```
Error in names(tables) <- paste(table_caps$label, table_caps$text, sep = " - ") : 
  'names' attribute [7] must be the same length as the vector [2] 

```
This is the error I end up. 

As i tried with your code 



```
yp <- epmc_search("title:(Acute myeloid leukemia drug studies) OPEN_ACCESS:Y")
There are no results matching your query
```
--
When i use this `Acute Myeloid Leukemia Drug` I m getting result but at the same time if i do this query `"Acute myeloid leukemia drug studies"` using europmc library I do get PMIDs not sure what I'm doing wrong 
 
  |  
 Let me know is going wrong here 

With regards



`

**Comment by cstubben** [comment]
In my example, I'm searching for matches in the title to limit the number of results.   I would test your searches at the Europe PMC site first, but this returns 35608 records.  You can always send me an email directly (see the DESCRIPTION file) if you have a specific question too. 

```
x <- epmc_search("Acute myeloid leukemia drug studies OPEN_ACCESS:Y") 
35608 records found, returning 100
```

**Comment by kcmtest** [comment]
wow cool I will directly mail to you. I was not sure if the reply will got
to you thats why i was posting it on github .



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/07/20,
23:36:11

**Comment by kcmtest** [comment]
Hello Chris this is my question which did post on stackoverflow ..

https://stackoverflow.com/questions/63138416/saving-tidypmc-output-which-forms-a-list-object-and-saving-it-into-individual-fi

If you can have a look and let me know how to resolve it.

I did use your code but i was not able to get the PMCID . But I fixed
by first searching on europmc library then pass the result to your library
. Meanwhile if you can tell me how do i do the same with your code where i
would like to save all the metadata and results which can be parsed and
stored that would be really helpful.

If you can see the stack question then you perhaps get my issue and the
solution I'm trying to find.

With regards





[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
28/07/20,
23:39:49
